level_0 = {
	"terrain": '../levels/0/level_0_terrain.csv',
	'coins': "../levels/0/level_0_coins.csv",
	"collided_trees": "../levels/0/level_0_collided_trees.csv",
	"grass1": "../levels/0/level_0_grass1.csv",
	"plants": "../levels/0/level_0_plants.csv",
	'crates': "../levels/0/level_0_crates.csv",
	"enemies": "../levels/0/level_0_ENEMIES.csv",
	'constraints': "../levels/0/level_0_constraints.csv",
	'player': "../levels/0/level_0_player.csv",
	'node_pos':(110,400),
	'unlock':1,
	'node_graphics': '../graphics/overworld/0',}
level_1 = {
	"terrain": '../levels/1/level_1_terrain.csv',
	'coins': "../levels/1/level_1_coins.csv",
	"collided_trees": "../levels/1/level_1_collided_trees.csv",
	"grass1": "../levels/1/level_1_grass1.csv",
	"plants": "../levels/1/level_1_plants.csv",
	'crates': "../levels/1/level_1_crates.csv",
	"enemies": "../levels/1/level_1_ENEMIES.csv",
	'constraints': "../levels/1/level_1_constraints.csv",
	'player': "../levels/1/level_1_player.csv",
	'node_pos':(300,220),
	'unlock':2,
	'node_graphics': '../graphics/overworld/1',}
level_2 = {
	"terrain": '../levels/2/level_2_terrain.csv',
	'coins': "../levels/2/level_2_coins.csv",
	"collided_trees": "../levels/2/level_2_collided_trees.csv",
	"grass1": "../levels/2/level_2_grass1.csv",
	"plants": "../levels/2/level_2_plants.csv",
	'crates': "../levels/2/level_2_crates.csv",
	"enemies": "../levels/2/level_2_ENEMIES.csv",
	'constraints': "../levels/2/level_2_constraints.csv",
	'player': "../levels/2/level_2_player.csv",
	'node_pos':(480,610),
	'unlock':3,
	'node_graphics': '../graphics/overworld/2',}
level_3 = {
	"terrain": '../levels/3/level_3_terrain.csv',
	'coins': "../levels/3/level_3_coins.csv",
	"collided_trees": "../levels/3/level_3_collided_trees.csv",
	"grass1": "../levels/3/level_3_grass1.csv",
	"plants": "../levels/3/level_3_plants.csv",
	'crates': "../levels/3/level_3_crates.csv",
	"enemies": "../levels/3/level_3_ENEMIES.csv",
	'constraints': "../levels/3/level_3_constraints.csv",
	'player': "../levels/3/level_3_player.csv",
	'node_pos':(610,350),
	'unlock':4,
	'node_graphics': '../graphics/overworld/3',} 
level_4 = {
	"terrain": '../levels/4/level_4_terrain.csv',
	'coins': "../levels/4/level_4_coins.csv",
	"collided_trees": "../levels/4/level_4_collided_trees.csv",
	"grass1": "../levels/4/level_4_grass1.csv",
	"plants": "../levels/4/level_4_plants.csv",
	'crates': "../levels/4/level_4_crates.csv",
	"enemies": "../levels/4/level_4_ENEMIES.csv",
	'constraints': "../levels/4/level_4_constraints.csv",
	'player': "../levels/4/level_4_player.csv",
	'node_pos':(880,210),
	'unlock':5,
	'node_graphics': '../graphics/overworld/4',}
level_5 = {
	"terrain": '../levels/0/level_0_terrain.csv',
	'coins': "../levels/0/level_0_coins.csv",
	"collided_trees": "../levels/0/level_0_collided_trees.csv",
	"grass1": "../levels/0/level_0_grass1.csv",
	"plants": "../levels/0/level_0_plants.csv",
	'crates': "../levels/0/level_0_crates.csv",
	"enemies": "../levels/0/level_0_ENEMIES.csv",
	'constraints': "../levels/0/level_0_constraints.csv",
	'player': "../levels/0/level_0_player.csv",
	'node_pos':(1050,400),
	'unlock':5,
	'node_graphics': '../graphics/overworld/5',}

levels = {
	0:level_0,
	1:level_1,
	2:level_2,
	3:level_3,
	4:level_4,
	5:level_5}